WFARTHA/Models/ProyectoSociedad.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Web.Mvc;
using WFARTHA.Entities;

namespace WFARTHA.Models
{
    public partial class ProyectoSociedad
    {

        [DataType(DataType.Text)]
        [DisplayName("Proyectos")]
        [UIHint("List")]
        public List<SelectListItem> proyectoLista { get; set; }
        public List<SelectListItem> sociedadLista { get; set; }

        public string ID_PSPNR { get; set; }
        public string NOMBRE { get; set; }
        public string ID_BUKRS { get; set; }
        public string BUTXT { get; set; }

        public ProyectoSociedad()
        {
            WFARTHAEntities data = new WFARTHAEntities();
            proyectoLista = new List<SelectListItem>();
            sociedadLista = new List<SelectListItem>();
            var qProyecto = from u in data.PROYECTOes  select u;
            var qSociedad = from s in data.SOCIEDADs where (s.ACTIVO == true) select s;
            var listData = qProyecto.ToList();
            var SociedadData = qSociedad.ToList();
            foreach (var Data in listData)
            {

                string proyecto = string.Format("{0} - {1}",
                Data.ID_PSPNR,
                Data.NOMBRE);
                proyectoLista.Add(new SelectListItem() {
                    Value = Data.ID_PSPNR.ToString(),
                    Text = proyecto,
                });
            }

            foreach (var Data in SociedadData)
            {
                string sociedad = string.Format("{0} - {1}",
                Data.BUKRS,
                Data.BUTXT);

                sociedadLista.Add(new SelectListItem()
                {
                    Value = Data.BUKRS.ToString(),
                    Text = sociedad,
                });
            }
        }
     
    }
    
}

WFARTHA/Controllers/Catalogos/ProyectoSociedadController.cs
using ExcelDataReader;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.HtmlControls;
using WFARTHA.Common;
using WFARTHA.Entities;
using WFARTHA.Models;
using WFARTHA.Services;

namespace TAT001.Controllers.Catalogos
{
    [Authorize]
    public class ProyectoSociedadController : Controller
    {

        private WFARTHAEntities db = new WFARTHAEntities();
        // GET: ProyectoSociedad
        public ActionResult Index()
        {
            int pagina = 721; //ID EN BASE DE DATOS
            FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
            var dET_PROYECTO_DEC_V = db.DET_PROYECTO_DEC_V;
            ProyectoSociedadNuevo un = new ProyectoSociedadNuevo();
            un.L = dET_PROYECTO_DEC_V.ToList();
            return View(un);
        }

        // GET: Usuarios/Create
        public ActionResult Create()
        {
            int pagina = 723; //ID EN BASE DE DATOS
            FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
            ProyectoSociedad obj = new ProyectoSociedad();
            return View(obj);
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "ID_PSPNR,ID_BUKRS")] ProyectoSociedad proyectoSociedad)
        {
            DET_PROYECTOV u = new DET_PROYECTOV();
            u.ID_PSPNR = proyectoSociedad.ID_PSPNR;
            u.ID_BUKRS = proyectoSociedad.ID_BUKRS;

            db.DET_PROYECTOV.Add(u);

            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Error = "El usuario ya existe. Introduzca un ID de usuario diferente";
                int pagina = 723; //ID EN BASE DE DATOS
                FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
                ProyectoSociedad obj = new ProyectoSociedad();
                return View(obj);
            }


        }

        public ActionResult Delete(String ID_PSPNR, String ID_BUKRS)
        {
            DET_PROYECTOV dET_PROYECTOV = db.DET_PROYECTOV.Find(ID_PSPNR, ID_BUKRS);
            db.DET_PROYECTOV.Remove(dET_PROYECTOV);
            db.SaveChanges();
            return RedirectToAction("Index");
          
        }
    }
}

WFARTHA/Views/ProyectoSociedad/Create.cshtml
@model WFARTHA.Models.ProyectoSociedad

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.pagina_r = 723;
    ViewBag.carpeta_r = 500;
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ProyectoSociedad</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        <div class=" dropdown col s12">
            @Html.LabelFor(model => model.ID_PSPNR, htmlAttributes: new { @id = "lbl_proyecto" })
            @Html.DropDownListFor(model => model.ID_PSPNR, Model.proyectoLista, "Seleccione un Proyecto", new { @class = "browser-default" })
            @Html.ValidationMessageFor(model => model.ID_PSPNR, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class=" dropdown col s12">
            @Html.LabelFor(model => model.ID_BUKRS, htmlAttributes: new { @id = "lbl_sociedad" })
            @Html.DropDownListFor(model => model.ID_BUKRS, Model.sociedadLista, "Seleccione Sociedad", new { @class = "browser-default" })
            @Html.ValidationMessageFor(model => model.ID_BUKRS, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WFARTHA/Views/ProyectoSociedad/Index.cshtml
@model WFARTHA.Models.ProyectoSociedadNuevo

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.pagina_r = 721;
    ViewBag.carpeta_r = 500;
}


<div class="row">
    <div class="col s12 right-align">
        <a class="btn-small" id="btn_nuevo" href="@Url.Action("Create")">Agregar</a>
        @*<a class="waves-effect waves-light btn modal-trigger" href="#modal1">Nuevo</a>*@
    </div>
</div>
<div class="card-panel">
    @*<div class="row">*@
    <div class="row" style="margin-bottom:0;">
        <div class="input-field col s3 m3 l3">
            <select id="selecc">
                <option value="10" selected>10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
            <label id="btn_length">Ver por página</label>
        </div>
        <div class="input-field col s3 m3 l3 offset-l6 offset-m6">
            <input type="text" class="global_filter" id="global_filter">
            <label for="global_filter" id="lbl_search">Buscar</label>
        </div>
    </div>
    <script>
        var elem = document.querySelector('select');
        var options = [];
        var instance = M.FormSelect.init(elem, options);
    </script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/dataTables.material.min.js"></script>
    <link href="~/Content/dataTable.css" rel="stylesheet" />
    <link href="//cdn.datatables.net/1.10.16/css/dataTables.material.min.css" rel="stylesheet" />
    <div style="width:100%;">
        <table class="table mdl-data-table striped" id="table" style="width:100%;">
            <thead>
                <tr>
                    <th class="lblSociedad">
                        @Html.DisplayName("PROYECTO")
                    </th>
                    <th class="lblUsuario">
                        @Html.DisplayName("SOCIEDAD")
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.L)
                {
                    <tr style="cursor:pointer">
                        <td>
                            @Html.DisplayFor(modelItem => item.NOMBRE)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BUTXT)
                        </td>
                        <td>
                            <a href="@Url.Action("Delete", "ProyectoSociedad", new { ID_PSPNR = item.ID_PSPNR , ID_BUKRS = item.ID_BUKRS})">
                                <i class='material-icons red-text'>delete</i>
                            </a>&nbsp;
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    @*</div>*@
</div>

<script type="text/javascript">
    $("a[data-form-method='post']").click(function (event) {
        event.preventDefault();
        var element = $(this);
        var action = element.attr("href");
        element.closest("form").each(function () {
            var form = $(this);
            form.attr("action", action);
            form.submit();
        });
    });
</script>
<script>
    $(document).ready(function () {
        var table = $('#table').DataTable({
            scrollY: "35vh",
            language: {
                "url": "../Scripts/lang/ES.json"
            },
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'mdl-data-table__cell--non-numeric'
                }
            ]
        });

        var a = $('#selecc').val();
        table.page.len(a).draw();
        $('#selecc').on('change', function () {
            table.page.len(this.value).draw();
        });

        $('input.global_filter').on('keyup click', function () {
            filterGlobal();
        });
    });

    function filterGlobal() {
        $('#table').DataTable().search(
            $('#global_filter').val()).draw();
    }

</script>

<style>

    .dataTables_length {
        display: none;
    }

    .dataTables_filter {
        display: none;
    }

    .dataTables_scrollHeadInner, .mdl-data-table {
        width: 100%;
    }
</style>