WFARTHA/Entities/APPSETTING.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPSETTING
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string VALUE { get; set; }
        public bool ACTIVO { get; set; }
    }
}

WFARTHA/Models/Appsetting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WFARTHA.Models
{
    public partial class Appsetting
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string VALUE { get; set; }
        public Boolean ACTIVO { get; set; }
    }
}

WFARTHA/Controllers/Catalogos/AppsettingController.cs
using ExcelDataReader;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.HtmlControls;
using WFARTHA.Common;
using WFARTHA.Entities;
using WFARTHA.Models;
using WFARTHA.Services;

namespace TAT001.Controllers.Catalogos
{
    [Authorize]
    public class AppsettingController : Controller
    {

        private WFARTHAEntities db = new WFARTHAEntities();



        public ActionResult Index()
        {
            int pagina = 921; //ID EN BASE DE DATOS
            FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
            var appsetting = db.APPSETTINGs;
            AppsettingNuevo un = new AppsettingNuevo();
            un.L = appsetting.ToList();
            return View(un);
        }


       // GET: Usuarios/Create
        public ActionResult Create()
        {
            int pagina = 923; //ID EN BASE DE DATOS
            FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
            return View();
        }


        [HttpPost]

        public ActionResult Create([Bind(Include = "NOMBRE,VALUE,ACTIVO")] Appsetting appsetting)
        {
            APPSETTING u = new APPSETTING();
            string nOMBRE = appsetting.NOMBRE.Replace(" ", "_");

            u.NOMBRE = nOMBRE;
            u.VALUE = appsetting.VALUE;
            u.ACTIVO = true;

            db.APPSETTINGs.Add(u);

            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch {
                ViewBag.Error = "El usuario ya existe. Introduzca un ID de usuario diferente";
                int pagina = 923; //ID EN BASE DE DATOS
                FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
                return View();
            }

        }

        public ActionResult Delete(int ID )
        {
            APPSETTING aPPSETTING = db.APPSETTINGs.Find( ID);
            aPPSETTING.ID = aPPSETTING.ID;
            aPPSETTING.NOMBRE = aPPSETTING.NOMBRE;
            aPPSETTING.VALUE = aPPSETTING.VALUE;
            aPPSETTING.ACTIVO = false;
            db.Entry(aPPSETTING).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");


        }


        public ActionResult Edit(int ID)
        {
            int pagina = 924; //ID EN BASE DE DATOS
            FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
            APPSETTING aPPSETTING = db.APPSETTINGs.Find(ID);
            return View(aPPSETTING);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NOMBRE,VALUE,ACTIVO")] APPSETTING aPPSETTING)
        {
            string nOMBRE = aPPSETTING.NOMBRE.Replace(" ", "_");
            aPPSETTING.ID = aPPSETTING.ID;
            aPPSETTING.NOMBRE = nOMBRE;
            aPPSETTING.VALUE = aPPSETTING.VALUE;
            aPPSETTING.ACTIVO = true;
            db.Entry(aPPSETTING).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int ID)
        {
            int pagina = 924; //ID EN BASE DE DATOS
            FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
            APPSETTING aPPSETTING = db.APPSETTINGs.Find(ID);
            return View(aPPSETTING);
        }

    }
}

WFARTHA/Views/Appsetting/Create.cshtml
@model WFARTHA.Models.Appsetting

@{
    /**/

    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.pagina_r = 923;
    ViewBag.carpeta_r = 900;
}


<script type="text/javascript" src="~/Scripts/jquery.validate.min.js"></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col s12 right-align">
            <button type="submit" id="btn_guardar" class="btn btn-default">Guardar</button>
        </div>
    </div>
    <div class="row">
        <div class="col s12 left-align">
            @if (@TempData["MensajeUsuario"] != null)
            {
                <label id="lbl_mensajeusuario"></label>
            }
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <div class="card-panel">
                <div class="row">
                    <div class="form-group">
                        <div class="input-field col s12">
                            @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.LabelFor(model => model.NOMBRE, htmlAttributes: new { @id = "lbl_nombre" })
                            @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-field col s12">
                            @Html.EditorFor(model => model.VALUE, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.LabelFor(model => model.VALUE, htmlAttributes: new { @id = "lbl_value" })
                            @Html.ValidationMessageFor(model => model.VALUE, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
<div>
    @Html.ActionLink("Back to List", "Index", null, new { id = "lbl_regresar" })
</div>
@if (ViewBag.Error != null)
{
    <script>
            M.toast({ html: '@ViewBag.Error', classes: 'red' });
    </script>
}

WFARTHA/Views/Appsetting/Details.cshtml
@model WFARTHA.Entities.APPSETTING

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.pagina_r = 922;
    ViewBag.carpeta_r = 900;
}


<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VALUE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VALUE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { ID = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WFARTHA/Views/Appsetting/Edit.cshtml
@model WFARTHA.Entities.APPSETTING

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.pagina_r = 924;
    ViewBag.carpeta_r = 900;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VALUE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VALUE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VALUE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WFARTHA/Views/Appsetting/Index.cshtml
@*@model IEnumerable<TAT001.Entities.APPSETTING>*@
@model WFARTHA.Models.AppsettingNuevo

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.pagina_r = 921;
    ViewBag.carpeta_r = 900;
}


<div class="row">
    <div class="col s12 right-align">
        <a class="btn-small" id="btn_nuevo" href="@Url.Action("Create")">Agregar</a>
    </div>
</div>
<div class="card-panel">
    @*<div class="row">*@
    <div class="row" style="margin-bottom:0;">
        <div class="input-field col s3 m3 l3">
            <select id="selecc">
                <option value="10" selected>10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
            <label id="btn_length">Ver por página</label>
        </div>
        <div class="input-field col s3 m3 l3 offset-l6 offset-m6">
            <input type="text" class="global_filter" id="global_filter">
            <label for="global_filter" id="lbl_search">Buscar</label>
        </div>
    </div>
    <script>
        var elem = document.querySelector('select');
        var options = [];
        var instance = M.FormSelect.init(elem, options);
    </script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/dataTables.material.min.js"></script>
    <link href="~/Content/dataTable.css" rel="stylesheet" />
    <link href="//cdn.datatables.net/1.10.16/css/dataTables.material.min.css" rel="stylesheet" />
    <div style="width:100%;">
        <table class="table mdl-data-table striped" id="table" style="width:100%;">
            <thead>
                <tr>
                    <th class="lblSociedad">
                        @Html.DisplayNameFor(model => model.L.FirstOrDefault().NOMBRE)
                    </th>
                    <th class="lblUsuario">
                        @Html.DisplayNameFor(model => model.L.FirstOrDefault().VALUE)
                    </th>
                    <th class="lblActivo">
                        @Html.DisplayName("ESTATUS")
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.L)
                {
                <tr style="cursor:pointer">
                    <td>
                        @Html.DisplayFor(modelItem => item.NOMBRE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VALUE)
                    </td>
                    @if (item.ACTIVO == false)
                    {
                        <td class="">
                            <span class="lbl_cancelled new badge red darken-1 white-text" data-badge-caption=" ">INACTIVO</span>
                        </td>
                    }
                    else
                    {
                        <td class="">
                            <span class="lbl_txt new badge green darken-1 white-text" data-badge-caption=" ">ACTIVO</span>
                        </td>
                    }



                    <td>
                        <a href="@Url.Action("Edit", "Appsetting", new { ID = item.ID })">
                            <i class='material-icons green-text'>edit</i>
                        </a>&nbsp;
                        <a href="@Url.Action("Delete", "Appsetting", new { ID = item.ID })">
                            <i class='material-icons red-text'>delete</i>
                        </a>&nbsp;
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    @*</div>*@
</div>

<script type="text/javascript">
    $("a[data-form-method='post']").click(function (event) {
        event.preventDefault();
        var element = $(this);
        var action = element.attr("href");
        element.closest("form").each(function () {
            var form = $(this);
            form.attr("action", action);
            form.submit();
        });
    });
</script>
<script>
    $(document).ready(function () {
        var table = $('#table').DataTable({
            scrollY: "35vh",
            language: {
                "url": "../Scripts/lang/ES.json"
            },
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'mdl-data-table__cell--non-numeric'
                }
            ]
        });

        var a = $('#selecc').val();
        table.page.len(a).draw();
        $('#selecc').on('change', function () {
            table.page.len(this.value).draw();
        });

        $('input.global_filter').on('keyup click', function () {
            filterGlobal();
        });
    });

    function filterGlobal() {
        $('#table').DataTable().search(
            $('#global_filter').val()).draw();
    }

</script>

<style>

    .dataTables_length {
        display: none;
    }

    .dataTables_filter {
        display: none;
    }

    .dataTables_scrollHeadInner, .mdl-data-table {
        width: 100%;
    }
</style>