WFARTHA/Models/SociedadesUsuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Web.Mvc;
using WFARTHA.Entities;

namespace WFARTHA.Models
{
    public class SociedadesUsuario
    {
        [DataType(DataType.Text)]
        [DisplayName("Sociedad")]
        [UIHint("List")]
        public List<SelectListItem> usersLista { get; set; }
        public List<SelectListItem> sociedadLista { get; set; }
        public List<SelectListItem> presupuestoLista { get; set; }



    
        public string BUKRS { get; set; }
        public string ID_USER { get; set; }
        public string TIPOPRE { get; set; }
        public string BUTXT { get; set; }
        public string NOMBRE { get; set; }
        public string DESC { get; set; }



        public SociedadesUsuario()
        {
            WFARTHAEntities data = new WFARTHAEntities();
            usersLista = new List<SelectListItem>();
            sociedadLista = new List<SelectListItem>();
            presupuestoLista = new List<SelectListItem>();
            var qUsuario = from u in data.USUARIOs where (u.ACTIVO == true) select u;
            var qSociedad = from s in data.SOCIEDADs where (s.ACTIVO == true) select s;
            var qPresupuesto = from p in data.TIPOPRESUPUESTOes where (p.ESTATUS == true) select p;
            var listData = qUsuario.ToList();
            var SociedadData = qSociedad.ToList();
            var PresupuestoData = qPresupuesto.ToList();
            foreach (var Data in listData)
            {

                string nombre = string.Format("{0} - {1} {2} {3}",
                Data.ID,
                Data.NOMBRE,
                Data.APELLIDO_P,
                Data.APELLIDO_M);


                usersLista.Add(new SelectListItem()
                {
                    Value = Data.ID.ToString(),
                    Text = nombre,
                });
            }

            foreach (var Data in SociedadData)
            {
                string sociedad = string.Format("{0} - {1}",
                Data.BUKRS,
                Data.BUTXT);

                sociedadLista.Add(new SelectListItem()
                {
                    Value = Data.BUKRS.ToString(),
                    Text = sociedad,
                });
            }

            foreach (var Data in PresupuestoData)
            {
                string presupuesto = string.Format("{0} - {1}",
                Data.TIPOPRE,
                Data.DESC);

                presupuestoLista.Add(new SelectListItem()
                {
                    Value = Data.TIPOPRE.ToString(),
                    Text = presupuesto,
                });
            }

        }

    }
}

WFARTHA/Controllers/Catalogos/SociedadesUsuarioController.cs
using ExcelDataReader;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.HtmlControls;
using WFARTHA.Common;
using WFARTHA.Entities;
using WFARTHA.Models;
using WFARTHA.Services;

namespace WFARTHA.Controllers.Catalogos
{
    [Authorize]
    public class SociedadesUsuarioController : Controller
    {

        private WFARTHAEntities db = new WFARTHAEntities();

        // GET: SociedadesUsuario
        public ActionResult Index()
        {
            int pagina = 881; //ID EN BASE DE DATOS
            FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
            var dET_TIPOPRESUPUESTOVs = db.DET_TIPOPRESUPUESTOV;
            SociedadesUsuarioNuevo un = new SociedadesUsuarioNuevo();
            un.L = dET_TIPOPRESUPUESTOVs.ToList();
            return View(un);
        }

        // GET: Usuarios/Create
        public ActionResult Create()
        {
            int pagina = 883; //ID EN BASE DE DATOS
            FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
            SociedadesUsuario obj = new SociedadesUsuario();
            return View(obj);
        }


        [HttpPost]
        public ActionResult Create([Bind(Include = "BUKRS,ID_USER,TIPOPRE")] SociedadesUsuario sociedadesUsuario)
        {
            DET_TIPOPRESUPUESTO u = new DET_TIPOPRESUPUESTO();
            u.BUKRS = sociedadesUsuario.BUKRS;
            u.ID_USER = sociedadesUsuario.ID_USER;
            u.TIPOPRE = sociedadesUsuario.TIPOPRE;
     

            db.DET_TIPOPRESUPUESTO.Add(u);

            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {

                ViewBag.Error = "El usuario ya existe. Introduzca un ID de usuario diferente";
                int pagina = 723; //ID EN BASE DE DATOS
                FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
                SociedadesUsuario obj = new SociedadesUsuario();
                return View(obj);

            }

        }


        public ActionResult Delete(String BUKRS, String ID_USER)
        {
            DET_TIPOPRESUPUESTO dET_TIPOPRESUPUESTO = db.DET_TIPOPRESUPUESTO.Find(BUKRS, ID_USER);
            db.DET_TIPOPRESUPUESTO.Remove(dET_TIPOPRESUPUESTO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Edit(String BUKRS, String ID_USER)
        {
            int pagina = 884; //ID EN BASE DE DATOS
            FnCommon.ObtenerConfPage(db, pagina, User.Identity.Name, this.ControllerContext.Controller);
            DET_TIPOPRESUPUESTO dET_TIPOPRESUPUESTO = db.DET_TIPOPRESUPUESTO.Find(BUKRS, ID_USER);
            return View(dET_TIPOPRESUPUESTO);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BUKRS,ID_USER,TIPOPRE")] DET_TIPOPRESUPUESTO dET_TIPOPRESUPUESTO)
        {

            dET_TIPOPRESUPUESTO.BUKRS = dET_TIPOPRESUPUESTO.BUKRS;
            dET_TIPOPRESUPUESTO.ID_USER = dET_TIPOPRESUPUESTO.ID_USER;
            dET_TIPOPRESUPUESTO.TIPOPRE = dET_TIPOPRESUPUESTO.TIPOPRE;

            db.Entry(dET_TIPOPRESUPUESTO).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }





    }
}

WFARTHA/Views/SociedadesUsuario/Create.cshtml
@model WFARTHA.Models.SociedadesUsuario

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.pagina_r = 883;
    ViewBag.carpeta_r = 500;
}




<script type="text/javascript" src="~/Scripts/jquery.validate.min.js"></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col s12 right-align">
            <button type="submit" id="btn_guardar" class="btn btn-default">Guardar</button>
        </div>
    </div>
    <div class="row">
        <div class="col s12 left-align">
            @if (@TempData["MensajeUsuario"] != null)
            {
                <label id="lbl_mensajeusuario"></label>
            }
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <div class="card-panel">
                <div class="row">
                    <div class="form-group">
                        <div class=" dropdown col s12">
                            @Html.LabelFor(model => model.BUKRS, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownListFor(model => model.BUKRS, Model.sociedadLista, "Seleccione Sociedad", new { @class = "browser-default" })
                            @Html.ValidationMessageFor(model => model.BUKRS, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class=" dropdown col s12">
                            @Html.LabelFor(model => model.ID_USER, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownListFor(model => model.ID_USER, Model.usersLista, "Seleccione Usuario", new { @class = "browser-default" })
                            @Html.ValidationMessageFor(model => model.ID_USER, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class=" dropdown col s12">

                            @Html.LabelFor(model => model.TIPOPRE, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownListFor(model => model.TIPOPRE, Model.presupuestoLista, "Seleccione Presupuesto", new { @class = "browser-default" })
                            @Html.ValidationMessageFor(model => model.TIPOPRE, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

}
<div>
    @Html.ActionLink("Back to List", "Index", null, new { id = "lbl_regresar" })
</div>
@if (ViewBag.Error != null)
{
    <script>
            M.toast({ html: '@ViewBag.Error', classes: 'red' });
    </script>



}

WFARTHA/Views/SociedadesUsuario/Edit.cshtml
@model WFARTHA.Entities.DET_TIPOPRESUPUESTO

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.pagina_r = 924;
    ViewBag.carpeta_r = 900;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DET_TIPOPRESUPUESTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BUKRS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BUKRS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BUKRS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_USER, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_USER, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_USER, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TIPOPRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TIPOPRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TIPOPRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WFARTHA/Views/SociedadesUsuario/Index.cshtml
@model WFARTHA.Models.SociedadesUsuarioNuevo

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.pagina_r = 881;
    ViewBag.carpeta_r = 500;
}


<div class="row">
    <div class="col s12 right-align">
        <a class="btn-small" id="btn_nuevo" href="@Url.Action("Create")">Agregar</a>
        @*<a class="waves-effect waves-light btn modal-trigger" href="#modal1">Nuevo</a>*@
    </div>
</div>
<div class="card-panel">
    @*<div class="row">*@
    <div class="row" style="margin-bottom:0;">
        <div class="input-field col s3 m3 l3">
            <select id="selecc">
                <option value="10" selected>10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
            <label id="btn_length">Ver por página</label>
        </div>
        <div class="input-field col s3 m3 l3 offset-l6 offset-m6">
            <input type="text" class="global_filter" id="global_filter">
            <label for="global_filter" id="lbl_search">Buscar</label>
        </div>
    </div>
    <script>
        var elem = document.querySelector('select');
        var options = [];
        var instance = M.FormSelect.init(elem, options);
    </script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/dataTables.material.min.js"></script>
    <link href="~/Content/dataTable.css" rel="stylesheet" />
    <link href="//cdn.datatables.net/1.10.16/css/dataTables.material.min.css" rel="stylesheet" />
    <div style="width:100%;">
        <table class="table mdl-data-table striped" id="table" style="width:100%;">
            <thead>
                <tr>
                    <th class="lblSociedad">
                        @Html.DisplayNameFor(model => model.L.FirstOrDefault().BUTXT)
                    </th>
                    <th class="lblUsuario">
                        @Html.DisplayNameFor(model => model.L.FirstOrDefault().NOMBRE)
                    </th>
                    <th class="lblPresupuesto">
                        @Html.DisplayNameFor(model => model.L.FirstOrDefault().DESC)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.L)
                {
                <tr style="cursor:pointer">
                    <td>
                        @Html.DisplayFor(modelItem => item.BUTXT)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NOMBRE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DESC)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "SociedadesUsuario", new { IBUKRS = item.BUKRS , ID_USER = item.ID_USER })">
                            <i class='material-icons green-text'>edit</i>
                        </a>&nbsp;
                        <a href="@Url.Action("Delete", "SociedadesUsuario", new { BUKRS = item.BUKRS , ID_USER = item.ID_USER })">
                            <i class='material-icons red-text'>delete</i>
                        </a>&nbsp;
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    @*</div>*@
</div>

<script type="text/javascript">
    $("a[data-form-method='post']").click(function (event) {
        event.preventDefault();
        var element = $(this);
        var action = element.attr("href");
        element.closest("form").each(function () {
            var form = $(this);
            form.attr("action", action);
            form.submit();
        });
    });
</script>
<script>
    $(document).ready(function () {
        var table = $('#table').DataTable({
            scrollY: "35vh",
            language: {
                "url": "../Scripts/lang/ES.json"
            },
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'mdl-data-table__cell--non-numeric'
                }
            ]
        });

        var a = $('#selecc').val();
        table.page.len(a).draw();
        $('#selecc').on('change', function () {
            table.page.len(this.value).draw();
        });

        $('input.global_filter').on('keyup click', function () {
            filterGlobal();
        });
    });

    function filterGlobal() {
        $('#table').DataTable().search(
            $('#global_filter').val()).draw();
    }

</script>

<style>

    .dataTables_length {
        display: none;
    }

    .dataTables_filter {
        display: none;
    }

    .dataTables_scrollHeadInner, .mdl-data-table {
        width: 100%;
    }
</style>